name: flutter_app_host
description: Quickly distribute your Flutter app to testers or enterprise users by uploading it to the AppHost hosting service
version: 0.4.1
homepage: https://github.com/apphost-plugins/flutter_app_host

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  path: ^1.8.3
  http: ^1.0.0